### ISSUE TITLE
Record of pixie16 repo issues. 

### ISSUE THREAD

**Issue by spaulaus** [spaulaus/paass-lc#123]
# Description
I needed to keep a record of all the issues in the original repositories. Many of them are still things that we need to address. 

# [pixie16/paass](https://github.com/pixie16/paass)
- [x] [pixie16/paass#301](https://github.com/pixie16/paass/issues/301)
- [x] [pixie16/paass#294](https://github.com/pixie16/paass/issues/294)
- [x] [pixie16/paass#293](https://github.com/pixie16/paass/issues/293)
- [x] [pixie16/paass#287](https://github.com/pixie16/paass/issues/287)
- [x] [pixie16/paass#286](https://github.com/pixie16/paass/issues/286)
- [x] [pixie16/paass#270](https://github.com/pixie16/paass/issues/270)
- [x] [pixie16/paass#199](https://github.com/pixie16/paass/issues/199)
- [x] [pixie16/paass#144](https://github.com/pixie16/paass/issues/144)
- [x] [pixie16/paass#143](https://github.com/pixie16/paass/issues/143)
- [x] [pixie16/paass#69](https://github.com/pixie16/paass/issues/69)
- [x] [pixie16/paass#14](https://github.com/pixie16/paass/issues/14)
- [x] [pixie16/paass#7](https://github.com/pixie16/paass/issues/7)

# [pixie16/pixie_scan](https://github.com/pixie16/pixie_scan)
- [x] [pixie16/pixie_scan#27](https://github.com/pixie16/pixie_scan/issues/27)
- [x] [pixie16/pixie_scan#23](https://github.com/pixie16/pixie_scan/issues/23)
- [x] [pixie16/pixie_scan#20](https://github.com/pixie16/pixie_scan/issues/20)
- [x] [pixie16/pixie_scan#19](https://github.com/pixie16/pixie_scan/issues/19)
- [x] [pixie16/pixie_scan#17](https://github.com/pixie16/pixie_scan/issues/17)
- [x] [pixie16/pixie_scan#16](https://github.com/pixie16/pixie_scan/issues/16)
- [x] [pixie16/pixie_scan#15](https://github.com/pixie16/pixie_scan/issues/15)
- [x] [pixie16/pixie_scan#14](https://github.com/pixie16/pixie_scan/issues/14)
- [x] [pixie16/pixie_scan#13](https://github.com/pixie16/pixie_scan/issues/13)
- [ ] [pixie16/pixie_scan#12](https://github.com/pixie16/pixie_scan/issues/12)
- [x] [pixie16/pixie_scan#11](https://github.com/pixie16/pixie_scan/issues/11)
- [x] [pixie16/pixie_scan#8](https://github.com/pixie16/pixie_scan/issues/8)

# [pixie16/PixieSuite2](https://github.com/pixie16/PixieSuite2)
- [x] [pixie16/PixieSuite2#101](https://github.com/pixie16/PixieSuite2/issues/101)
- [x] [pixie16/PixieSuite2#85](https://github.com/pixie16/PixieSuite2/issues/85)
- [x] [pixie16/PixieSuite2#69](https://github.com/pixie16/PixieSuite2/issues/69)
- [x] [pixie16/PixieSuite2#7](https://github.com/pixie16/PixieSuite2/issues/7)
- [x] [pixie16/PixieSuite2#4](https://github.com/pixie16/PixieSuite2/issues/4)
- [x] [pixie16/PixieSuite2#3](https://github.com/pixie16/PixieSuite2/issues/3)

**Comment by spaulaus** [comment]
Technically, pixie16/paass#14 isn't really complete. We can just ignore it since we're using ROOT to plot.

**Comment by spaulaus** [comment]
pixie16/pixie_scan#23 is a Won't Fix. The histogram plotting in VandleProcessor, should not have any cuts imposed on it. That way users can view the raw histograms.

**Comment by spaulaus** [comment]
This issue was moved to spaulaus/paass#123
